### ISSUE TITLE
Some things about the pre-trained model

### ISSUE THREAD

**Issue by nounotabe** [psychopa4/PFNL#13]
Hi, thank you for sharing this nice job!
I have some confusions about the pre-trained model provided in Google Drive.
It seems that the checkpoint of PFNL could not achieve the results presented in the paper using **model.testvideos()** (e.g. I got 23.0454dB and 0.8111 for PSNR and SSIM when evaluating 'calendar' in Vid4, which are 24.37dB and 0.8246 in the paper). Is there any modification in the test code or checkpoint? or did I calculate the PSNR and SSIM uncorretly?
Here is the code I used to calculate the PSNR and SSIM in MATLAB.  The first and last two frames have been kept out. 
```matlab
image_sr = imread(strcat(file_path_sr,image_name_sr));
image_sr = im2double(image_sr);
image_sr = rgb2gray(image_sr);

image_hr = imread(strcat(file_path_hr,image_name_hr));
image_hr = im2double(image_hr);
image_hr = rgb2gray(image_hr);
        
p = psnr(image_sr(9:end-8,9:end-8), image_hr(9:end-8,9:end-8))
s = ssim(image_sr, image_hr)
```
Looking forward to your reply!

**Comment by darrenf0209** [comment]
Hey @nounotabe , while I am not one of the authors, I had the same trouble as you.

I believe the authors addressed the issue [here](https://github.com/psychopa4/PFNL/issues/7#issuecomment-572845335). The following link should be accessible for the [Matlab](https://drive.google.com/drive/folders/17q8-WADZ2layyaFQct0iKttsla4FAU2B) scripts used by the authors.

I believe there is a difference in results due to slightly different implementations.

Hope that helps!

**Comment by nounotabe** [comment]
> Hey @nounotabe , while I am not one of the authors, I had the same trouble as you.
> 
> I believe the authors addressed the issue [here](https://github.com/psychopa4/PFNL/issues/7#issuecomment-572845335). The following link should be accessible for the [Matlab](https://drive.google.com/drive/folders/17q8-WADZ2layyaFQct0iKttsla4FAU2B) scripts used by the authors.
> 
> I believe there is a difference in results due to slightly different implementations.
> 
> Hope that helps!

It helps a lot! Many thanks for your kind suggestion!
